---
# tasks file for install_nginx
- name: ensure nginx is at the latest version
  apt:
    update_cache: yes
    name:  nginx
    state: latest
- name: start nginx
  service:
    name:  nginx
    state: started