---
# tasks file for install_nginx
- name: ensure nginx is at the latest version
  apt:
    update_cache: true
    name:  nginx
    state: latest
  become: true
  become_user: maxim
  become_method: sudo
- name: start nginx
  service:
    name:  nginx
    state: started