---
# tasks file for config_nginx
- name: "create www directory for site1"
    file:
      path: /var/www/html/{{ domain }}1
      state: directory
      mode: '0775'
      owner: "{{ user }}"
      group: "{{ user }}"

- name: "create www directory for site2"
    file:
      path: /var/www/html/{{ domain }}2
      state: directory
      mode: '0775'
      owner: "{{ user }}"
      group: "{{ user }}"

- name: "copy index1.html"
    template:
      src: index1.html
      dest: //var/www/html/{{ domain }}1.html
      owner: "{{ user }}"
      group: "{{ user }}"

- name: "copy index2.html"
    template:
      src: index2.html
      dest: //var/www/html/{{ domain }}2.html
      owner: "{{ user }}"
      group: "{{ user }}"

- name: "copy nginx site1.conf"
    template:
      src: {{ domain }}1.conf
      dest: /etc/nginx/sites-available/{{ domain }}1.conf
      owner: root
      group: root
      mode: '0644'

- name: "copy nginx site2.conf"
    template:
      src: {{ domain }}2.conf
      dest: /etc/nginx/sites-available/{{ domain }}2.conf
      owner: root
      group: root
      mode: '0644'

- name: "create symlink for site1"
    file:
      src: /etc/nginx/sites-available/{{ domain }}1.conf
      dest: /etc/nginx/sites-enabled/{{ domain }}1.conf
      state: link

- name: "create symlink for site2"
    file:
      src: /etc/nginx/sites-available/{{ domain }}2.conf
      dest: /etc/nginx/sites-enabled/{{ domain }}2.conf
      state: link

- name: "nginx restart"
    service:
      name: nginx
      state: restarted